
package org.prodageo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AsyncTestResponseImpl", targetNamespace = "http://prodageo.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AsyncTestResponseImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "response", targetNamespace = "http://prodageo.org/", className = "org.prodageo.Response")
    @ResponseWrapper(localName = "responseResponse", targetNamespace = "http://prodageo.org/", className = "org.prodageo.ResponseResponse")
    public void response(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
