
package org.prodageo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AsyncTestResponseImplService", targetNamespace = "http://prodageo.org/", wsdlLocation = "file:/home/fbaucher/NetBeansProjects/AsyncWs/dist/AsyncTestResponseImplService.wsdl")
public class AsyncTestResponseImplService
    extends Service
{

    private final static URL ASYNCTESTRESPONSEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.prodageo.AsyncTestResponseImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.prodageo.AsyncTestResponseImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/fbaucher/NetBeansProjects/AsyncWs/dist/AsyncTestResponseImplService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/fbaucher/NetBeansProjects/AsyncWs/dist/AsyncTestResponseImplService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ASYNCTESTRESPONSEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public AsyncTestResponseImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsyncTestResponseImplService() {
        super(ASYNCTESTRESPONSEIMPLSERVICE_WSDL_LOCATION, new QName("http://prodageo.org/", "AsyncTestResponseImplService"));
    }

    /**
     * 
     * @return
     *     returns AsyncTestResponseImpl
     */
    @WebEndpoint(name = "AsyncTestResponseImplPort")
    public AsyncTestResponseImpl getAsyncTestResponseImplPort() {
        return super.getPort(new QName("http://prodageo.org/", "AsyncTestResponseImplPort"), AsyncTestResponseImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AsyncTestResponseImpl
     */
    @WebEndpoint(name = "AsyncTestResponseImplPort")
    public AsyncTestResponseImpl getAsyncTestResponseImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://prodageo.org/", "AsyncTestResponseImplPort"), AsyncTestResponseImpl.class, features);
    }

}
