// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.prodageo.exa6023.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import org.prodageo.exa6023.client.managed.request.ApplicationEntityTypesProcessor;
import org.prodageo.exa6023.client.managed.request.ApplicationRequestFactory;
import org.prodageo.exa6023.client.managed.request.BaseProxy;
import org.prodageo.exa6023.client.managed.request.PizzaOrderProxy;
import org.prodageo.exa6023.client.managed.request.PizzaProxy;
import org.prodageo.exa6023.client.managed.request.ToppingProxy;
import org.prodageo.exa6023.client.managed.ui.BaseListView;
import org.prodageo.exa6023.client.managed.ui.BaseMobileListView;
import org.prodageo.exa6023.client.managed.ui.PizzaListView;
import org.prodageo.exa6023.client.managed.ui.PizzaMobileListView;
import org.prodageo.exa6023.client.managed.ui.PizzaOrderListView;
import org.prodageo.exa6023.client.managed.ui.PizzaOrderMobileListView;
import org.prodageo.exa6023.client.managed.ui.ToppingListView;
import org.prodageo.exa6023.client.managed.ui.ToppingMobileListView;
import org.prodageo.exa6023.client.scaffold.ScaffoldApp;
import org.prodageo.exa6023.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleTopping(ToppingProxy isNull) {
                setResult(new ToppingListActivity(requests, ScaffoldApp.isMobile() ? ToppingMobileListView.instance() : ToppingListView.instance(), placeController));
            }

            @Override
            public void handlePizza(PizzaProxy isNull) {
                setResult(new PizzaListActivity(requests, ScaffoldApp.isMobile() ? PizzaMobileListView.instance() : PizzaListView.instance(), placeController));
            }

            @Override
            public void handlePizzaOrder(PizzaOrderProxy isNull) {
                setResult(new PizzaOrderListActivity(requests, ScaffoldApp.isMobile() ? PizzaOrderMobileListView.instance() : PizzaOrderListView.instance(), placeController));
            }

            @Override
            public void handleBase(BaseProxy isNull) {
                setResult(new BaseListActivity(requests, ScaffoldApp.isMobile() ? BaseMobileListView.instance() : BaseListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
