// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.prodageo.exa6023.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import org.prodageo.exa6023.client.managed.activity.PizzaEditActivityWrapper.View;
import org.prodageo.exa6023.client.managed.request.ApplicationRequestFactory;
import org.prodageo.exa6023.client.managed.request.BaseProxy;
import org.prodageo.exa6023.client.managed.request.PizzaProxy;
import org.prodageo.exa6023.client.managed.request.ToppingProxy;
import org.prodageo.exa6023.client.managed.ui.ToppingSetEditor;
import org.prodageo.exa6023.client.scaffold.activity.IsScaffoldMobileActivity;
import org.prodageo.exa6023.client.scaffold.place.ProxyEditView;
import org.prodageo.exa6023.client.scaffold.place.ProxyListPlace;
import org.prodageo.exa6023.client.scaffold.place.ProxyPlace;

public abstract class PizzaEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setToppingsPickerValues(Collections.<ToppingProxy>emptyList());
        requests.toppingRequest().findToppingEntries(0, 50).with(org.prodageo.exa6023.client.managed.ui.ToppingProxyRenderer.instance().getPaths()).fire(new Receiver<List<ToppingProxy>>() {

            public void onSuccess(List<ToppingProxy> response) {
                List<ToppingProxy> values = new ArrayList<ToppingProxy>();
                values.add(null);
                values.addAll(response);
                view.setToppingsPickerValues(values);
            }
        });
        view.setBasePickerValues(Collections.<BaseProxy>emptyList());
        requests.baseRequest().findBaseEntries(0, 50).with(org.prodageo.exa6023.client.managed.ui.BaseProxyRenderer.instance().getPaths()).fire(new Receiver<List<BaseProxy>>() {

            public void onSuccess(List<BaseProxy> response) {
                List<BaseProxy> values = new ArrayList<BaseProxy>();
                values.add(null);
                values.addAll(response);
                view.setBasePickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends org.prodageo.exa6023.client.scaffold.place.ProxyEditView<org.prodageo.exa6023.client.managed.request.PizzaProxy, V>> extends ProxyEditView<PizzaProxy, V> {

        void setToppingsPickerValues(Collection<ToppingProxy> values);

        void setBasePickerValues(Collection<BaseProxy> values);
    }
}
