<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2008/07/30 12:46:20


$this->setDatabase('propel', new sfPropelDatabase(array (
  'phptype' => 'mysql',
  'dsn' => 'mysql://root@localhost/scratch',
  'name' => 'propel',
)));
