<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2008/07/28 16:58:05


$this->setDatabase('propel', new sfPropelDatabase(array (
  'phptype' => 'mysql',
  'database' => NULL,
  'dsn' => 'mysql://root:@localhost/cllajinet',
  'name' => 'propel',
)));
