// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.prodageo.exa6023.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

public abstract class ApplicationEntityTypesProcessor<T> {

    private final T defaultValue;

    private T result;

    public ApplicationEntityTypesProcessor() {
        defaultValue = null;
    }

    public ApplicationEntityTypesProcessor(T defaultValue) {
        this.defaultValue = defaultValue;
    }

    public static Set<java.lang.Class<? extends com.google.gwt.requestfactory.shared.EntityProxy>> getAll() {
        Set<Class<? extends EntityProxy>> rtn = new HashSet<Class<? extends EntityProxy>>();
        rtn.add(ToppingProxy.class);
        rtn.add(PizzaProxy.class);
        rtn.add(PizzaOrderProxy.class);
        rtn.add(BaseProxy.class);
        return Collections.unmodifiableSet(rtn);
    }

    private static void process(org.prodageo.exa6023.client.managed.request.ApplicationEntityTypesProcessor<?> processor, Class<?> clazz) {
        if (ToppingProxy.class.equals(clazz)) {
            processor.handleTopping((ToppingProxy) null);
            return;
        }
        if (PizzaProxy.class.equals(clazz)) {
            processor.handlePizza((PizzaProxy) null);
            return;
        }
        if (PizzaOrderProxy.class.equals(clazz)) {
            processor.handlePizzaOrder((PizzaOrderProxy) null);
            return;
        }
        if (BaseProxy.class.equals(clazz)) {
            processor.handleBase((BaseProxy) null);
            return;
        }
        processor.handleNonProxy(null);
    }

    private static void process(org.prodageo.exa6023.client.managed.request.ApplicationEntityTypesProcessor<?> processor, Object proxy) {
        if (proxy instanceof ToppingProxy) {
            processor.handleTopping((ToppingProxy) proxy);
            return;
        }
        if (proxy instanceof PizzaProxy) {
            processor.handlePizza((PizzaProxy) proxy);
            return;
        }
        if (proxy instanceof PizzaOrderProxy) {
            processor.handlePizzaOrder((PizzaOrderProxy) proxy);
            return;
        }
        if (proxy instanceof BaseProxy) {
            processor.handleBase((BaseProxy) proxy);
            return;
        }
        processor.handleNonProxy(proxy);
    }

    public void handleNonProxy(Object object) {
    }

    public abstract void handleTopping(ToppingProxy proxy);

    public abstract void handlePizza(PizzaProxy proxy);

    public abstract void handlePizzaOrder(PizzaOrderProxy proxy);

    public abstract void handleBase(BaseProxy proxy);

    public T process(Class<?> clazz) {
        setResult(defaultValue);
        ApplicationEntityTypesProcessor.process(this, clazz);
        return result;
    }

    public T process(Object proxy) {
        setResult(defaultValue);
        ApplicationEntityTypesProcessor.process(this, proxy);
        return result;
    }

    protected void setResult(T result) {
        this.result = result;
    }
}
