// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.prodageo.exa6023.client.managed.request;

import org.prodageo.exa6023.shared.gae.MakesGaeRequests;
import org.prodageo.exa6023.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory, MakesGaeRequests {

    ToppingRequest toppingRequest();

    PizzaRequest pizzaRequest();

    PizzaOrderRequest pizzaOrderRequest();

    BaseRequest baseRequest();
}
