// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.prodageo.exa6023.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.Set;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.prodageo.exa6023.server.domain.Pizza")
@ProxyForName("org.prodageo.exa6023.server.domain.Pizza")
public interface PizzaProxy extends EntityProxy {

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);

    abstract String getName();

    abstract void setName(String name);

    abstract Float getPrice();

    abstract void setPrice(Float price);

    abstract Set<org.prodageo.exa6023.client.managed.request.ToppingProxy> getToppings();

    abstract void setToppings(Set<ToppingProxy> toppings);

    abstract BaseProxy getBase();

    abstract void setBase(BaseProxy base);
}
