// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.prodageo.exa6023.client.managed.ui;

import com.google.gwt.text.shared.AbstractRenderer;
import org.prodageo.exa6023.client.managed.request.ApplicationEntityTypesProcessor;
import org.prodageo.exa6023.client.managed.request.BaseProxy;
import org.prodageo.exa6023.client.managed.request.PizzaOrderProxy;
import org.prodageo.exa6023.client.managed.request.PizzaProxy;
import org.prodageo.exa6023.client.managed.request.ToppingProxy;
import org.prodageo.exa6023.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleTopping(ToppingProxy isNull) {
                setResult("Toppings");
            }

            @Override
            public void handlePizza(PizzaProxy isNull) {
                setResult("Pizzas");
            }

            @Override
            public void handlePizzaOrder(PizzaOrderProxy isNull) {
                setResult("PizzaOrders");
            }

            @Override
            public void handleBase(BaseProxy isNull) {
                setResult("Bases");
            }
        }.process(object.getProxyClass());
    }
}
