// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.prodageo.exa6023.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.requestfactory.client.RequestFactoryEditorDriver;
import com.google.gwt.requestfactory.shared.RequestFactory;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import java.util.Collection;
import java.util.List;
import java.util.Set;
import org.prodageo.exa6023.client.managed.activity.PizzaOrderEditActivityWrapper;
import org.prodageo.exa6023.client.managed.activity.PizzaOrderEditActivityWrapper.View;
import org.prodageo.exa6023.client.managed.request.PizzaOrderProxy;
import org.prodageo.exa6023.client.managed.request.PizzaProxy;
import org.prodageo.exa6023.client.scaffold.place.ProxyEditView;
import org.prodageo.exa6023.client.scaffold.ui.*;
import org.prodageo.exa6023.shared.PaymentType;

public abstract class PizzaOrderMobileEditView_Roo_Gwt extends Composite implements View<PizzaOrderMobileEditView> {

    @UiField
    TextBox name;

    @UiField
    TextBox address;

    @UiField
    FloatBox total;

    @UiField(provided = true)
    ValueListBox<PaymentType> paymentType = new ValueListBox<PaymentType>(new AbstractRenderer<org.prodageo.exa6023.shared.PaymentType>() {

        public String render(org.prodageo.exa6023.shared.PaymentType obj) {
            return obj == null ? "" : String.valueOf(obj);
        }
    });

    @UiField
    DateBox deliveryDate;

    @UiField
    PizzaSetEditor pizzas;

    public void setPaymentTypePickerValues(Collection<PaymentType> values) {
        paymentType.setAcceptableValues(values);
    }

    public void setPizzasPickerValues(Collection<PizzaProxy> values) {
        pizzas.setAcceptableValues(values);
    }
}
