// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.prodageo.exa6023.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;
import org.prodageo.exa6023.client.managed.request.BaseProxy;
import org.prodageo.exa6023.client.managed.request.PizzaProxy;
import org.prodageo.exa6023.client.managed.request.ToppingProxy;
import org.prodageo.exa6023.client.scaffold.place.AbstractProxyListView;

public abstract class PizzaListView_Roo_Gwt extends AbstractProxyListView<PizzaProxy> {

    @UiField
    CellTable<PizzaProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<PizzaProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(PizzaProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("version");
        table.addColumn(new TextColumn<PizzaProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(PizzaProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
        paths.add("name");
        table.addColumn(new TextColumn<PizzaProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(PizzaProxy object) {
                return renderer.render(object.getName());
            }
        }, "Name");
        paths.add("price");
        table.addColumn(new TextColumn<PizzaProxy>() {

            Renderer<java.lang.Float> renderer = new AbstractRenderer<java.lang.Float>() {

                public String render(java.lang.Float obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(PizzaProxy object) {
                return renderer.render(object.getPrice());
            }
        }, "Price");
        paths.add("toppings");
        table.addColumn(new TextColumn<PizzaProxy>() {

            Renderer<java.util.Set> renderer = org.prodageo.exa6023.client.scaffold.place.CollectionRenderer.of(org.prodageo.exa6023.client.managed.ui.ToppingProxyRenderer.instance());

            @Override
            public String getValue(PizzaProxy object) {
                return renderer.render(object.getToppings());
            }
        }, "Toppings");
        paths.add("base");
        table.addColumn(new TextColumn<PizzaProxy>() {

            Renderer<org.prodageo.exa6023.client.managed.request.BaseProxy> renderer = org.prodageo.exa6023.client.managed.ui.BaseProxyRenderer.instance();

            @Override
            public String getValue(PizzaProxy object) {
                return renderer.render(object.getBase());
            }
        }, "Base");
    }
}
