// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.prodageo.exa6023.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;
import org.prodageo.exa6023.client.managed.request.PizzaOrderProxy;
import org.prodageo.exa6023.client.managed.request.PizzaProxy;
import org.prodageo.exa6023.client.scaffold.place.AbstractProxyListView;
import org.prodageo.exa6023.shared.PaymentType;

public abstract class PizzaOrderListView_Roo_Gwt extends AbstractProxyListView<PizzaOrderProxy> {

    @UiField
    CellTable<PizzaOrderProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<PizzaOrderProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(PizzaOrderProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("version");
        table.addColumn(new TextColumn<PizzaOrderProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(PizzaOrderProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
        paths.add("name");
        table.addColumn(new TextColumn<PizzaOrderProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(PizzaOrderProxy object) {
                return renderer.render(object.getName());
            }
        }, "Name");
        paths.add("address");
        table.addColumn(new TextColumn<PizzaOrderProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(PizzaOrderProxy object) {
                return renderer.render(object.getAddress());
            }
        }, "Address");
        paths.add("total");
        table.addColumn(new TextColumn<PizzaOrderProxy>() {

            Renderer<java.lang.Float> renderer = new AbstractRenderer<java.lang.Float>() {

                public String render(java.lang.Float obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(PizzaOrderProxy object) {
                return renderer.render(object.getTotal());
            }
        }, "Total");
        paths.add("paymentType");
        table.addColumn(new TextColumn<PizzaOrderProxy>() {

            Renderer<org.prodageo.exa6023.shared.PaymentType> renderer = new AbstractRenderer<org.prodageo.exa6023.shared.PaymentType>() {

                public String render(org.prodageo.exa6023.shared.PaymentType obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(PizzaOrderProxy object) {
                return renderer.render(object.getPaymentType());
            }
        }, "Payment Type");
        paths.add("deliveryDate");
        table.addColumn(new TextColumn<PizzaOrderProxy>() {

            Renderer<java.util.Date> renderer = new DateTimeFormatRenderer(DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_MEDIUM));

            @Override
            public String getValue(PizzaOrderProxy object) {
                return renderer.render(object.getDeliveryDate());
            }
        }, "Delivery Date");
        paths.add("pizzas");
        table.addColumn(new TextColumn<PizzaOrderProxy>() {

            Renderer<java.util.Set> renderer = org.prodageo.exa6023.client.scaffold.place.CollectionRenderer.of(org.prodageo.exa6023.client.managed.ui.PizzaProxyRenderer.instance());

            @Override
            public String getValue(PizzaOrderProxy object) {
                return renderer.render(object.getPizzas());
            }
        }, "Pizzas");
    }
}
