// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.prodageo.exa6023.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import org.prodageo.exa6023.client.managed.activity.PizzaOrderEditActivityWrapper.View;
import org.prodageo.exa6023.client.managed.request.ApplicationRequestFactory;
import org.prodageo.exa6023.client.managed.request.PizzaOrderProxy;
import org.prodageo.exa6023.client.managed.request.PizzaProxy;
import org.prodageo.exa6023.client.managed.ui.PizzaSetEditor;
import org.prodageo.exa6023.client.scaffold.activity.IsScaffoldMobileActivity;
import org.prodageo.exa6023.client.scaffold.place.ProxyEditView;
import org.prodageo.exa6023.client.scaffold.place.ProxyListPlace;
import org.prodageo.exa6023.client.scaffold.place.ProxyPlace;
import org.prodageo.exa6023.shared.PaymentType;

public abstract class PizzaOrderEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setPaymentTypePickerValues(Arrays.asList(PaymentType.values()));
        view.setPizzasPickerValues(Collections.<PizzaProxy>emptyList());
        requests.pizzaRequest().findPizzaEntries(0, 50).with(org.prodageo.exa6023.client.managed.ui.PizzaProxyRenderer.instance().getPaths()).fire(new Receiver<List<PizzaProxy>>() {

            public void onSuccess(List<PizzaProxy> response) {
                List<PizzaProxy> values = new ArrayList<PizzaProxy>();
                values.add(null);
                values.addAll(response);
                view.setPizzasPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends org.prodageo.exa6023.client.scaffold.place.ProxyEditView<org.prodageo.exa6023.client.managed.request.PizzaOrderProxy, V>> extends ProxyEditView<PizzaOrderProxy, V> {

        void setPaymentTypePickerValues(Collection<PaymentType> values);

        void setPizzasPickerValues(Collection<PizzaProxy> values);
    }
}
